name: token-refresh -- Build and Publish to ECR

on:
  push:
    paths:
      - 'token_refresh/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        working-directory: ./token_refresh
        run: |
          docker build -t ${{ secrets.ECR_REPO_URL }}:latest .

      - name: Tag Docker image
        run: |
          docker tag ${{ secrets.ECR_REPO_URL }}:latest ${{ secrets.ECR_REPO_URL }}:latest

      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.ECR_REPO_URL }}:latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}